# Exercises

### #1 - Calculate the BMI (body mass index) on the two lists below using NDArrays...

In [6]:
# formula = weight / (height**2) * 730

import numpy as np
weights = np.array([110, 120, 130, 140, 150, 160, 170])  # in kilograms
heights = np.array([69, 70, 71, 72, 73, 74, 75])  # in meters

bmi_values = weights / (heights**2) * 730

print("BMI values:", bmi_values)

BMI values: [16.86620458 17.87755102 18.82562984 19.71450617 20.54794521 21.32943755
 22.06222222]


### #2 - Create a function that will take in two parameters and will create a random matrix based off of those parameters. Extra: Have additional parameters taken in that allow the user to choose the shape and data type of the matrix.

In [1]:
import numpy as np

def create_random_matrix(rows, columns, shape='random', dtype=float):
    """
    Create a random matrix based on the given parameters.

    Parameters:
    - rows: Number of rows in the matrix.
    - columns: Number of columns in the matrix.
    - shape: (Optional) Shape of the matrix. Default is 'random'. Other options include 'zeros' and 'ones'.
    - dtype: (Optional) Data type of the matrix. Default is float.

    Returns:
    - A NumPy array representing the random matrix.
    """

    if shape == 'random':
        matrix = np.random.rand(rows, columns)
    elif shape == 'zeros':
        matrix = np.zeros((rows, columns), dtype=dtype)
    elif shape == 'ones':
        matrix = np.ones((rows, columns), dtype=dtype)
    else:
        raise ValueError("Invalid shape. Supported shapes are 'random', 'zeros', and 'ones'.")

    return matrix.astype(dtype)

# Example usage:
rows = 4
columns = 5 
random_matrix = create_random_matrix(rows, columns)
print("Random Matrix:")
print(random_matrix)

zeros_matrix = create_random_matrix(rows, columns, shape='zeros', dtype=int)
print("\nZeros Matrix:")
print(zeros_matrix)

ones_matrix = create_random_matrix(rows, columns, shape='ones', dtype=float)
print("\nOnes Matrix:")
print(ones_matrix)




Random Matrix:
[[0.53458269 0.59674012 0.4430897  0.26315899 0.92145387]
 [0.53174158 0.12997294 0.95009604 0.18836225 0.2376219 ]
 [0.09192275 0.00310626 0.83642673 0.75805463 0.09466537]
 [0.87108069 0.91863561 0.08254144 0.90934202 0.46121737]]

Zeros Matrix:
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]

Ones Matrix:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


### #3 - Extra: Open and load the data in the two text files that have the Boston Red Sox hitting data for the past seasons. Compare the difference in the two years by putting the data into an NDArray and running a differencial operation on it. The column to look for will be SLG.

Your output should display which year (either 2017 or 2018) was a better year based on SLG

In [6]:
import csv
import numpy as np



In [ ]:
FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]

#Use this function to actually open the data inside of a NDArray


